// <auto-generated />
using System;
using Capgemini.API.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Capgemini.API.Migrations
{
    [DbContext(typeof(CapgeminiContext))]
    partial class CapgeminiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Capgemini.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppartamentNo");

                    b.Property<string>("City");

                    b.Property<string>("CompanyName");

                    b.Property<string>("HauseNo");

                    b.Property<string>("NIP");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<bool>("SalesActive");

                    b.Property<string>("Street");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Capgemini.Domain.OrderHeder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTime>("OrderDate");

                    b.Property<string>("OrderNummber");

                    b.Property<decimal>("OrderValue");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("OrderHeders");
                });

            modelBuilder.Entity("Capgemini.Domain.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("HederId");

                    b.Property<string>("OrderNummber");

                    b.Property<decimal>("Price");

                    b.Property<Guid>("ProductNo");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("HederId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Capgemini.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("QuantityOnStock");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Capgemini.Domain.OrderLine", b =>
                {
                    b.HasOne("Capgemini.Domain.OrderHeder", "Heder")
                        .WithMany("Lines")
                        .HasForeignKey("HederId");
                });
#pragma warning restore 612, 618
        }
    }
}
